name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: install_cunit_ubuntu
      run: sudo apt-get install libcunit1 libcunit1-doc libcunit1-dev
    - name: Run unit tests
      run: make test
    - name: Memory test
      run: make mem_test
